# Generated by Django 4.2.1 on 2023-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.FloatField(max_length=30)),
                ('val2', models.FloatField(max_length=30)),
                ('val3', models.FloatField(max_length=30)),
                ('val4', models.FloatField(max_length=30)),
                ('val5', models.FloatField(max_length=30)),
                ('val6', models.FloatField(max_length=30)),
                ('val7', models.FloatField(max_length=30)),
                ('val8', models.FloatField(max_length=30)),
                ('val9', models.FloatField(max_length=30)),
                ('val10', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(choices=[('AG', 'Ag'), ('NIFE', 'NiFe2O4'), ('AL', 'Al2O3'), ('BI', 'Bi2O3'), ('CO', 'CoO'), ('CR', 'Cr2O3'), ('FE', 'Fe2O3'), ('IN', 'In2O3'), ('LA', 'La2O3'), ('NO', 'NiO'), ('SB', 'Sb2O3'), ('SN', 'SnO2'), ('TI', 'TiO2'), ('V', 'V2O3'), ('W', 'WO3'), ('Y', 'Y2O3'), ('ZN', 'ZnO'), ('ZR', 'ZrO2'), ('PT', 'Pt')], max_length=15)),
                ('me', models.CharField(choices=[('CC', 'CC50'), ('LC', 'LC50'), ('EC', 'EC50')], max_length=15)),
                ('bt', models.CharField(choices=[('RAW', 'RAW 264.7 (M)'), ('A', 'A549 (H)'), ('HACAT', 'HaCaT (H)'), ('DR', 'Danio rerio (embryos)'), ('PS', 'Pseudokirchneriella subcapitata')], max_length=15)),
                ('ns', models.CharField(choices=[('SPHERE', 'spherical'), ('IRREG', 'irregular'), ('POLY', 'polyhedral'), ('N/A', 'n/a')], max_length=15)),
                ('dm', models.CharField(choices=[('WATER', 'H2O'), ('DRY', 'Dry'), ('DULBECCO', 'DMEM')], max_length=15)),
                ('ta', models.CharField(choices=[('FOUR', '4'), ('TWOFOUR', '24'), ('FOUREIGHT', '48'), ('SEVENTWO', '72'), ('NINESIX', '96'), ('ONETWENTY', '120'), ('ONESIXTYEIGHT', '168')], max_length=15)),
                ('sc', models.CharField(choices=[('PDAD', 'PDADMAC'), ('U', 'UC'), ('OLE', 'oleate')], max_length=15)),
                ('f1', models.FloatField(max_length=100)),
                ('f2', models.FloatField(max_length=100)),
                ('f3', models.FloatField(max_length=100)),
                ('f4', models.FloatField(max_length=100)),
                ('f5', models.FloatField(max_length=100)),
                ('f6', models.FloatField(max_length=100)),
                ('f7', models.FloatField(max_length=100)),
                ('f8', models.FloatField(max_length=100)),
                ('f9', models.FloatField(max_length=100)),
                ('f10', models.FloatField(max_length=100)),
            ],
        ),
    ]
